# Generated by Django 3.2.8 on 2021-10-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20211014_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='liked_by',
            new_name='commented_by',
        ),
    ]
