# Generated by Django 3.2.8 on 2021-10-16 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20211016_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.post'),
        ),
    ]
